#!/usr/bin/env bash

RUSTC=$(pwd)/vendor/rust/x86_64-unknown-linux-gnu/stage2/bin/rustc
EMCC=$(pwd)/vendor/emscripten/emcc

$RUSTC --emit ir --out-dir output source/main.rs &&
$EMCC --js-library source/library.js output/main.ll &&
node a.out.js
