#!/usr/bin/env bash

rm -rf vendor/emscripten-fastcomp/tools/clang
cp -r vendor/emscripten-fastcomp-clang vendor/emscripten-fastcomp/tools/clang
mkdir -p vendor/emscripten-fastcomp/build
cd vendor/emscripten-fastcomp/build
cmake .. \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_TARGETS_TO_BUILD="X86;JSBackend" \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DCLANG_INCLUDE_EXAMPLES=OFF \
	-DCLANG_INCLUDE_TESTS=OFF &&
make -j4
